name: NodeJS with Webpack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Test
      run: |
        npm ci
        sudo apt-get install chromium-browser
        npm test -- --no-watch

    - name: Build
      run: |
        npm ci
        npm run build -- --configuration=production
